architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/shfa.accesswidener")
}

dependencies {
    modCompileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
}

jar {
    manifest {
        attributes 'Automatic-Module-Name': 'com.ryanbester.shfa'
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    repositories {

    }
}
